// Generated by https://quicktype.io
import { Users } from "@prisma/client";
import { Request } from "express";

// Generated by https://quicktype.io

export interface IUser {
  _id: string;
  name: string;
  email: string;
  role: Role;
  active: boolean;
  avatar: string;
  password: string;
  passwordConfirm: string;
  passwordChangedAt: string;
  passwordRestToken: string;
  passwordRestExpires: string;
}

export enum Role {
  Admin = "admin",
  User = "user",
}

// Generated by https://quicktype.io
export interface IDecoded {
  id: string;
  phoneNumber: string;
  iat: number;
  exp: number;
}
export interface IRequest extends Request {
  user: Users;
}
export interface IError extends Error {
  name: string;
  code?: number;
  statusCode?: number;
  stringValue?: string;
  kind?: string;
  status?: string;
  path?: string;
  value?: string;
  errmsg?: string;
  isOperational?: boolean;
}
