// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IUser {
  id: string;
  name: string;
  avatarUrl: string;
  phoneNumber: string;
  email: string;
  createdAt: string;
  updatedAt: string;
  role: Role;
  Profile: IProfiles;
}

export interface IProfiles {
  id: string;
  title: string;
  description: string;
  location: string;
  phone: string;
  realState: string;
  price: number;
  constructionDate: Date;
  category: string;
  tag: string;
  province: string;
  city: string;
  amenities: string;
  rules: string;
  published: boolean | null;
  imagePath: string | null;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
export enum Role {
  Admin = "admin",
  User = "user",
}
